/**
 * Provider-neutral LLM contract.
 *
 * The swarm doesn't care whether a turn is generated by Claude, Gemini or a
 * GitHub-Models GPT — it just calls `complete()`. Each concrete provider maps
 * this shape onto its own wire format. The `id` is what the budget router uses
 * to count usage per provider against each one's free-tier cap.
 */
export type Role = "user" | "assistant";

export interface Msg {
  role: Role;
  content: string;
}

export interface CompleteOpts {
  /** Cacheable system prefix (the agent's persona). */
  system: string;
  messages: Msg[];
  maxTokens?: number;
  temperature?: number;
  /** Agents may prefer a provider so different models give different voices. */
  preferProvider?: string;
}

export interface LLM {
  /** Stable provider key used for budget accounting, e.g. "gemini". */
  readonly id: string;
  complete(opts: CompleteOpts): Promise<string>;
}
